try more bat things

diff --git a/templates/construct/post_install.bat.j2 b/templates/construct/post_install.bat.j2
--- a/templates/construct/post_install.bat.j2
+++ b/templates/construct/post_install.bat.j2
@@ -6,17 +6,21 @@
 @ECHO ON
 
 set POST_INSTALL_LOG=%PREFIX%\post_install.log
+set SETTINGS_PATH=%PREFIX%\{{ win_settings_path }}
+set OVERRIDES_PATH=%SETTINGS_PATH%\overrides.json
 
-echo "start" >> %POST_INSTALL_LOG%
+echo "0.0: start" >> "%POST_INSTALL_LOG%"
 
-md /s /q "%PREFIX%\{{ win_settings_path }}" ^
-    || echo 'directory might already exist' ^
-    >> "%POST_INSTALL_LOG%"
+md /s /q "%SETTINGS_PATH%" || echo "0.1: directory might already exist" >> "%POST_INSTALL_LOG%"
 
-echo ^
-    "{{ win_overrides }}" ^
-    > "%PREFIX%\{{ win_settings_path }}\overrides.json" ^
-    || echo "failed to write overrides" ^ 
-    >> %POST_INSTALL_LOG%
+echo "1.0: ensured %SETTINGS_PATH%" >> "%POST_INSTALL_LOG%"
 
-echo "done" >> %POST_INSTALL_LOG%
+set OVERRIDES="{{ win_overrides }}"
+
+echo "2.0: created overrides env var for %OVERRIDES%" >> "%POST_INSTALL_LOG%"
+
+echo "%OVERRIDES%" > "%OVERRIDES_PATH%" || echo "2.1: failed to write overrides" >> "%POST_INSTALL_LOG%"
+
+echo "3.0: wrote overrides" >> "%POST_INSTALL_LOG%"
+
+echo "4.0: done" >> "%POST_INSTALL_LOG%"
